### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by yjacks** [linuxdeepin/dtkcommon#2]
编译一切正常，以下是安装报告
环境:Debian Bullseye,x86_64,编译已安装,已尽力排错
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_lib.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_lib.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_lib.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_lib.prf: file format not recognized
make: [Makefile:423：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_testcase.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_testcase.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_testcase.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_testcase.prf: file format not recognized
make: [Makefile:425：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_module.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_module.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_module.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_module.prf: file format not recognized
make: [Makefile:427：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_build.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_build.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_build.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_build.prf: file format not recognized
make: [Makefile:429：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_translation.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_translation.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_translation.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_translation.prf: file format not recognized
make: [Makefile:431：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_build_config.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_build_config.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_build_config.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_build_config.prf: file format not recognized
make: [Makefile:433：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_cmake.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_cmake.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_cmake.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_cmake.prf: file format not recognized
make: [Makefile:435：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_qmake.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_qmake.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_qmake.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_qmake.prf: file format not recognized
make: [Makefile:437：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_multiversion.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_multiversion.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_multiversion.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_multiversion.prf: file format not recognized
make: [Makefile:439：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_install_multiversion.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_install_multiversion.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_install_multiversion.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_install_multiversion.prf: file format not recognized
make: [Makefile:441：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/features/dtk_install_dconfig.prf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_install_dconfig.prf
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_install_dconfig.prf
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dtk_install_dconfig.prf: file format not recognized
make: [Makefile:443：install_prf] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/cmake/Dtk/DtkConfig.cmake /usr/lib//cmake/Dtk/DtkConfig.cmake
strip /usr/lib//cmake/Dtk/DtkConfig.cmake
strip: /usr/lib//cmake/Dtk/DtkConfig.cmake: file format not recognized
make: [Makefile:463：install_cmake_dtk] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/cmake/Dtk/DtkInstallDConfigConfig.cmake /usr/lib//cmake/Dtk/DtkInstallDConfigConfig.cmake
strip /usr/lib//cmake/Dtk/DtkInstallDConfigConfig.cmake
strip: /usr/lib//cmake/Dtk/DtkInstallDConfigConfig.cmake: file format not recognized
make: [Makefile:465：install_cmake_dtk] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/qt_lib_dtkcommon.pri /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcommon.pri
strip /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcommon.pri
strip: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dtkcommon.pri: file format not recognized
make: [Makefile:476：install_dtkcommon_module] 错误 1 (已忽略）
/usr/lib/qt5/bin/qmake -install qinstall -exe /home/jack/Data/dtkcommon/schemas/com.deepin.dtk.gschema.xml /usr/share/glib-2.0/schemas/com.deepin.dtk.gschema.xml
strip /usr/share/glib-2.0/schemas/com.deepin.dtk.gschema.xml
strip: /usr/share/glib-2.0/schemas/com.deepin.dtk.gschema.xml: file format not recognized

**Comment by ClayStan** [comment]
如果在 debian 上打包和安装，请使用 https://salsa.debian.org/pkg-deepin-team/dtkcommon
